---
# tasks file for snappass-docker

- file:
    path: /usr/share/source/snappass
    state: absent
  become: yes

- set_fact:
    namespace: "{{ 'jameswthorn' if snappass_repo_url.find('jameswthorn')>-1 else 'pinterest' }}"
    branch:    "{{ 'api' if snappass_repo_url.find('jameswthorn')>-1 else 'master' }}"

- name: "Check out {{ snappass_repo_url }}:{{ branch }}"
  git:
    repo: "{{ snappass_repo_url }}"
    dest: /usr/share/source/snappass
    version: "{{ branch }}"
  become: yes

- docker_image:
    path: /usr/share/source/snappass
    state: present
    name: "{{ namespace }}/snappass:{{ branch }}"

- name: Get dockerhost
  shell: /sbin/ip route | awk '/docker0/ { print $NF }'
  register: dockerhost_response

- set_fact:
    dockerhost_ip:    "{{ dockerhost_response.stdout }}"

- set_fact:
    redis_url: "redis://:{{ snappass_redis_password }}@{{ dockerhost_ip }}:{{ snappass_redis_port }}/{{ snappass_redis_db }}"

- name: Generate a secret key
  command: python -c 'import os; print(os.urandom(16))'
  register: result

- set_fact:
    secret_key: result.stdout

- docker_container:
    name:  "{{ snappass_container_name }}"
    image: "{{ namespace }}/snappass:{{ branch }}"
    ports: "{{ snappass_port }}:5000"
    state: started
    env:
      SECRET_KEY: "{{ secret_key }}"
      NO_SSL: True
      REDIS_URL:  "{{ redis_url }}"
      TZ: America/New_York
  register: snappass_container

- name: Wait until snappass is available
  wait_for: port={{ snappass_port }} delay=3
  when: snappass_container.changed